theme: minima
title: Yetanothr
author: CaptainTuesday
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description for this magnificent site built with coffee, git, githu & jekyll

# social links
twitter_username: wipedroot # DO NOT include the @ character, or else the build will fail!
github_username:  wipedroot # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
